# fly.toml app configuration file generated for thryft-ship-take-home on 2024-07-17T23:50:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thryft-ship-take-home'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
